#import "@preview/basic-document-props:0.1.0": simple-page

// Document configuration
#let document-author = "isomo"

// Document setup
#set document(
  title: "Empirical Modeling of Computational Trade-offs and Constraint Scaling for Classical Cryptographic Primitives in Succinct Zero-Knowledge Proofs",
  author: document-author,
  date: datetime.today(),
)

// Page setup
#set page(
  numbering: "1",
  number-align: center,
)

// Heading styles with numbering
#set heading(numbering: "1.1.1.")
#show heading.where(level: 1): set text(size: 16pt, weight: "bold")
#show heading.where(level: 2): set text(size: 14pt, weight: "bold")
#show heading.where(level: 3): set text(size: 12pt, weight: "bold")

// Citation styling
#show cite: set text(fill: blue)

// Table caption positioning - put captions above tables
#show figure.where(kind: table): it => [
  #it.caption
  #it.body
]

// Color shorthand functions
#let redt(content) = text(fill: red, content)
#let bluet(content) = text(fill: blue, content)
#let greent(content) = text(fill: green, content)
#let yellowt(content) = text(fill: yellow, content)
#let oranget(content) = text(fill: orange, content)
#let purplet(content) = text(fill: purple, content)
#let greyt(content) = text(fill: gray, content)
#let grayt(content) = text(fill: gray, content)

// Review scoring function
#let score-box(title, score, max-score: 10) = rect(width: 100%, stroke: 1pt, inset: 8pt, fill: luma(250), [
  #text(weight: "bold")[#title: ] #text(fill: blue, weight: "bold")[#score/#max-score]
])

// Comment box function
#let comment-box(title, content) = rect(width: 100%, stroke: 1pt, inset: 10pt, [
  #text(weight: "bold", size: 11pt)[#title]
  #v(0.5em)
  #content
])

// Title page
#align(center)[
  #text(size: 18pt, weight: "bold")[
    Academic Paper Review Report
  ]
  #v(0.5em)
  #text(size: 12pt)[
    Reviewer: #document-author
    Review Date: #datetime.today().display("[year]-[month]-[day]")
  ]
]

#v(1em)

// Paper information section
#rect(width: 100%, stroke: 1pt, inset: 10pt, fill: luma(245), [
  #text(weight: "bold", size: 14pt)[Paper Information]

  #grid(
    columns: (auto, 1fr),
    gutter: 1em,
    [*Paper Title:*], [Empirical Modeling of Computational Trade-offs and Constraint Scaling for Classical Cryptographic Primitives in Succinct Zero-Knowledge Proofs],
    [*Version:*], [1.0],
    [*Authors:*], [Abirami S.K, Karpagam G.R],
    [*Journal/Conference:*], [Scientific Reports],
  )
])

#v(1em)

// This section is for the author response.
= Review Summary

This manuscript sets out to characterize, in a reproducible containerized environment, the performance trade-off between classical public-key primitives (ECC and RSA) and their realization inside zero-knowledge proof (ZKP) systems. The paper reports a large classical key-generation latency advantage for ECC ($approx 400 times$ over RSA-2048), a claimed "resource inversion" in which ECC-style circuits consume more prover memory than RSA-style circuits, and two empirical "constraint scaling laws": a linear law $C approx 213 n + beta$ for ECC-friendly primitives and a multiplicative law $C approx 10(b dot r) + epsilon$ for RSA-style iteration. The topic is timely and the containerized, open-data methodology is commendable in spirit.

However, the manuscript has a #redt[*fundamental conceptual flaw that the experiments do not actually test the claim the paper makes*], compounded by scaling "laws" that are tautological by construction, internally inconsistent numerical reporting, very small sample sizes for the central result, and thin novelty over an already well-studied area. These are not surface defects fixable by editing; they require redesigning the core experiments and reframing the contribution. #redt[*Recommendation: Reject.*] (A substantially redesigned study could be resubmitted; see the constructive path in the closing comments.)

*Key issues:*

+ *The ZKP experiments do not benchmark ECC or RSA.* The entire framing — title, abstract, "resource inversion," and the scaling laws — is about ECC vs. RSA inside ZKP. But the circuits actually measured in Sections 5–6 are #oranget[not ECC and not RSA]. The "ECC-friendly archetype" is a Poseidon hash construction (`pedersenzkid.zok`) plus a Merkle tree; the "RSA-style archetype" is an RSA *accumulator* surrogate (`rsaaccumulator.zok`) modeling iterated modular exponentiation. Poseidon is a ZK-native hash function, *not* elliptic-curve cryptography; a modexp accumulator is *not* the RSA cryptosystem. The paper itself calls them "archetypes" and "surrogates," yet then draws conclusions about "ECC" and "RSA." The central narrative is therefore not supported by the data collected.

+ *The "scaling laws" are tautologies, not empirical discoveries.* The circuits are generated by "programmatically rewriting circuit headers" to repeat a fixed unit $n$ times. A chain of $n$ Poseidon permutations necessarily has $approx ("constraints per permutation") times n$ constraints; a Merkle tree of depth $d$ necessarily has $approx ("constraints per level") times d$; an accumulator of $b$-bit exponent repeated $r$ times necessarily costs $approx ("per-bit") times (b dot r)$. Recovering $C approx 213 n$ (with $R^2 = 1.0000$) is arithmetic, not science: 213 is simply the known R1CS cost of one Poseidon permutation. An $R^2$ of essentially 1 is a *red flag* that the relationship was built in, not measured.

+ *Numbers are internally inconsistent across the manuscript.* The abstract reports peak memory of #oranget[59.3 MiB vs 46.0 MiB] (20–40%), but Table 3 and Section 6.2 report #oranget[66.5 ± 6.5 vs 50.0 ± 1.2 MiB] ("33% higher"). Section 4.4 states classical peak memory "close to 95 MiB," while Section 5.2 reports compile memory of 140–155 MiB and proof memory of 51–57 MiB. "Proving time" is 0.0052/0.0063 s in Table 3 but 0.0342/0.0477 s in Fig. 4B. The scaling constant is variously "213," "213 ± ε," and "213–245 constraints per operation" (the latter silently merging Poseidon and Merkle). These discrepancies must be reconciled before any quantitative claim can be trusted.

+ *The headline "resource inversion" rests on $n = 3$ and tiny circuits.* The flagship finding (Table 3) compares two $approx 260$-constraint circuits with $n = 3$ replicates, giving 66.5 ± 6.5 vs 50.0 ± 1.2 MiB. The relative standard deviation on the ECC number is $approx 10%$, the circuits are minuscule, and the authors concede the Groth16 backend "dominates the runtime" and "masks" arithmetic differences at this scale. Naming a general "Resource Inversion phenomenon" from a single underpowered comparison at one tiny operating point is unwarranted.

+ *Large-RSA prover resources were never measured.* The appendix states the largest RSA configurations run in `compile-only` mode because full proof generation "may exceed 128 GiB of RAM." Consequently, the prover-side memory/time conclusions for large RSA are not backed by measurement. The "Compilation Paradox" (RSA compiles faster despite more constraints) is reported as a finding but neither explained nor controlled — it is most plausibly an artifact of compiling many copies of one identical sub-circuit.

+ *Novelty is thin.* The classical ECC-vs-RSA comparison in Section 4 is extensively documented in prior work; the manuscript itself notes its results "match earlier studies." The constraint costs of Poseidon, Merkle paths, and RSA accumulators are known from their defining papers. Reference [6] already benchmarks ZK-friendly hash functions and SNARK proving systems. The claim of being "the first comprehensive examination" is overstated.

+ *Statistical treatment is shallow and partly misapplied.* A $t$-test yielding "$p$ effectively zero" over 1000 iterations is uninformative (any nonzero effect is significant at that $N$); reporting it adds nothing. OLS $R^2$ is applied to data that is linear by construction. The meaningful comparisons (memory inversion) lack confidence intervals, effect sizes, or adequate replication.

+ *Writing and presentation need substantial work.* Numerous run-together words and typos ("imporant," "trade-off,although," "generation.Because," "level.For," "faster at 17.99 ± 0.16 seconds.This"), the overloaded use of "ECC" to mean three different things (secp256r1 keygen, Poseidon, "ECC-friendly"), and low-resolution figures whose annotated values disagree with the tables.


// This section is for the editor and supports the review above.
= Detailed Review

== Innovation Assessment

#score-box("Innovation Score", "3", max-score: 10)

The motivating question — how the cost of cryptographic operations changes when they move from native execution into an arithmetic-circuit/ZKP setting — is genuinely interesting and practically relevant for privacy-preserving systems. #bluet[The containerized, open-data framing and the explicit attempt to make ZKP cost predictable are the right instincts.]

Unfortunately, the realized contribution is much narrower than the framing. #oranget[Section 4 reproduces the well-established result that ECC key generation is far faster than RSA] — the manuscript concedes this "matches earlier studies." The ZKP portion does not study ECC or RSA at all (see §1 of the summary); it studies Poseidon/Merkle and a modular-exponentiation accumulator, whose per-unit R1CS costs are already known from their originating papers. #purplet[Recovering those known per-unit costs by repeating a unit circuit and fitting a line is not a new finding.] The "first comprehensive examination" claim is undercut by existing ZK-hash/SNARK benchmarking work, including the authors' own reference [6].

For this to be innovative, the paper would need to either (a) actually arithmetize ECC and RSA *cryptosystem* operations (e.g., ECDSA verification, RSA signature verification) inside the circuit and measure those, or (b) derive a scaling model that is *not* a direct consequence of how the benchmark circuits were assembled.

== Technical Quality Assessment

#score-box("Technical Quality Score", "3", max-score: 10)

The most serious technical problem is the #redt[mismatch between claims and instruments]. The paper repeatedly refers to "ECC-friendly" and "RSA-style" results as if they characterize ECC and RSA, but:

- *Poseidon ≠ ECC.* Poseidon is a ZK-native sponge hash defined over the scalar field; it has no elliptic-curve group operation. Using it as a stand-in for "ECC" and then concluding things about "ECC in ZKP" is a category error. A faithful ECC-in-ZKP workload would arithmetize curve point addition/scalar multiplication (non-native field) — which is *expensive*, not cheap, and would likely invert the paper's qualitative story.

- *RSA accumulator ≠ RSA cryptosystem.* The surrogate "precisely models the gate-depth costs of repeated squaring," but an accumulator's parameterization ($b times r$) is not the RSA encryption/verification workload, and the chosen "comparable baseline scale ($approx 260$ constraints)" makes the two archetypes match only at a trivially small size.

Second, the *constraint scaling laws* (Eqs. 1–2, Table 4) are not derived or measured in any nontrivial sense. Because each circuit is $n$ identical copies of a unit, $C(n) = c_0 + c_1 n$ with $c_1$ equal to the unit cost is guaranteed; $R^2 approx 1$ confirms only that the generator is deterministic. The "multiplicative" RSA model $C approx 10(b dot r)$ is likewise linear in the product $b dot r$; calling it "super-linear" only by treating it "as a one-variable function" is a presentation choice, not a property of the primitive.

Third, the *security-level annotations are meaningless for the surrogates.* Fig. 4 claims a "128-bit vs 112-bit" security advantage for the ECC-friendly archetype. A Poseidon hash chain and an RSA accumulator do not have comparable, well-defined "security levels" in this setup; this comparison should be removed.

Fourth, the *resource-inversion mechanism is asserted, not analyzed.* No evidence is given that the extra Poseidon memory is intrinsic to "field-native hashing" rather than an artifact of ZoKrates' witness layout for that particular circuit at $n=3$. A credible claim would require (i) larger circuits where the backend no longer dominates, (ii) a memory breakdown by phase and data structure, and (iii) many more replicates.

== Experimental Assessment

#score-box("Experimental Score", "3", max-score: 10)

#bluet[Strengths:] the use of a fixed Docker image (`zokrates/zokrates:0.8.7`), Groth16 over BN254, a documented measurement cadence (10 Hz Docker Stats), and a public repository with a pinned commit are all good reproducibility practices, and the SHA-256 baseline (≈27,214 constraints) is a reasonable anchor.

#oranget[However, the experimental design cannot support the conclusions:]

+ *Underpowered central result.* $n = 3$ for the memory-inversion comparison and $n = 5$ elsewhere, on $approx 260$-constraint circuits, with the backend admittedly masking arithmetic effects. The flagship "33%" gap (66.5 ± 6.5 vs 50.0 ± 1.2) is fragile given the variance and $N$.

+ *Unmeasured regime.* Large RSA proof generation was not run (compile-only, >128 GiB). Prover-resource conclusions for the large tier are therefore extrapolations, yet they are presented as results.

+ *Inconsistent operating conditions.* Memory is quoted at several different values across §4.4 (≈95 MiB), §5.2 (140–155 / 51–57 MiB), the abstract (59.3 / 46.0 MiB), and Table 3 (66.5 / 50.0 MiB). Classical power/latency are reported at different frequencies elsewhere in the authors' framework. Cross-metric interpretation is not possible until these are reconciled and a single, clearly defined measurement protocol is stated.

+ *Confounded "Compilation Paradox."* Faster RSA compilation despite higher constraint count is reported without controlling for circuit structure (repeated identical sub-circuits compress/optimize differently than heterogeneous ones). This is presented as an insight but is more likely a tooling artifact.

+ *Missing baselines and ablations.* There is no faithful in-circuit ECC or RSA workload, no comparison across proving systems beyond Groth16 (PLONK/Halo2 are only mentioned as future work, yet they would change the very constants being "discovered"), and no isolation of framework baseline memory (~95 MiB) from circuit-attributable memory.

== Writing Quality Assessment

#score-box("Writing Quality Score", "4", max-score: 10)

The manuscript is broadly readable and follows a conventional structure, and the methods section communicates the pipeline reasonably well. #bluet[The declarations, data-availability statement, and reproducibility appendix are appropriately detailed.]

#oranget[That said, the writing needs significant revision:]

- *Semantic slippage:* "ECC" is used to mean (1) secp256r1 key generation, (2) the Poseidon "ECC-friendly archetype," and (3) "ECC-friendly" generically. This conflation is the linguistic root of the conceptual flaw and must be fixed; the surrogates should never be called "ECC" or "RSA" without qualification.
- *Typographical errors and run-together words:* e.g., "imporant," "trade-off,although," "generation.Because," "use cases.For," "level.For," "much faster at 17.99 ± 0.16 seconds.This," "(+20–40%)." A careful proofreading pass is needed throughout.
- *Figures:* several figures are low-resolution and their in-figure annotations (e.g., proving times in Fig. 4B, memory bars in Fig. 3) disagree with the corresponding tables. Axis labels and units (MiB vs. MB) should be standardized.
- *Overclaiming:* "first comprehensive examination," "scaling laws," and "phenomenon" overstate what was established; the language should be calibrated to the (much smaller) evidence.


= Specific Revision Suggestions

== Major Issues

+ *Align experiments with claims.* Either (a) arithmetize genuine ECC and RSA *cryptosystem* operations in-circuit (e.g., non-native curve arithmetic for an ECDSA/ECDH check; modular exponentiation for an actual RSA verification) and benchmark those, or (b) honestly retitle and reframe the paper as a study of Poseidon/Merkle vs. RSA-accumulator surrogates — and drop all "ECC vs RSA in ZKP" conclusions.

+ *Replace tautological "scaling laws" with something measured.* If the per-unit constraint cost is fixed by the building block, say so and cite it; do not present it as an empirical law with $R^2 = 1$. A genuine contribution would model effects that are *not* baked in: compiler optimization across repeated structure, proving-system dependence of the constant, or witness-memory growth that is not linear.

+ *Reconcile all numbers.* Produce one table with a single, defined measurement protocol (phase, frequency, units, $N$) and make the abstract, body, tables, and figure annotations agree exactly.

+ *Power the central result.* Re-run the memory comparison with substantially larger $N$, across multiple circuit sizes large enough that the Groth16 backend no longer dominates, and report CIs/effect sizes. Only then can "resource inversion" be claimed.

+ *Either measure large-RSA proving or remove the claims.* If >128 GiB is the limit, restrict prover-resource conclusions to the measured regime and clearly label the rest as unmeasured.

== Minor Issues

+ *Remove meaningless security-level comparisons* ("128-bit vs 112-bit") for the surrogate circuits.

+ *Explain or drop the "Compilation Paradox,"* with a controlled experiment isolating circuit-structure effects from constraint count.

+ *Drop the uninformative $t$-test* (or replace with a reported effect size); $p approx 0$ at $N=1000$ conveys no useful information.

+ *Standardize units and clean figures* (MiB vs MB; regenerate low-resolution plots; reconcile in-figure values with tables).

+ *Proofread thoroughly* for the run-together words and typos listed above.

+ *Calibrate claims:* avoid "first comprehensive," "scaling laws," and "phenomenon" unless the evidence is strengthened to match.


= Review Comments

== Comments to Authors

Thank you for a clearly motivated study on an important and timely topic; the containerized, open-data methodology and the attempt to make ZKP cost predictable are genuinely valuable directions. #bluet[Your reproducibility practices (pinned image, pinned commit, documented cadence, public datasets) are a real strength and should be retained in any future version.]

My central concern is that #purplet[the paper's experiments do not measure the quantities the paper is about.] The title, abstract, and conclusions speak about ECC and RSA inside zero-knowledge proofs, but the ZKP circuits you benchmark are a Poseidon-based construction, a Merkle tree, and an RSA-*accumulator* surrogate. Poseidon is not elliptic-curve cryptography, and an accumulator is not the RSA cryptosystem; faithfully arithmetizing real ECC point operations would in fact be *costly* (non-native field arithmetic) and would likely reverse the qualitative story you tell. Because of this mismatch, the headline conclusions — "resource inversion" and the hybrid-architecture recommendation — are not established by your data.

A second, related concern is that the "constraint scaling laws" are consequences of how the benchmark circuits are assembled (repeating a fixed unit $n$ times), so recovering $C approx 213 n$ with $R^2 = 1$ is arithmetic rather than discovery. Combined with internally inconsistent numbers (the memory figures in the abstract, §4.4, §5.2, and Table 3 disagree; "proving time" differs between Table 3 and Fig. 4), an $n=3$ flagship comparison on ~260-constraint circuits, and the fact that large-RSA proving was never actually run, I do not think the current manuscript can support its conclusions.

I want to be constructive: there is a publishable paper here if you (1) either benchmark genuine in-circuit ECC/RSA operations or honestly reframe the work around the surrogates you actually measured; (2) replace the tautological laws with a model of something not built in by construction; (3) reconcile every number under one stated protocol; and (4) substantially increase replication and circuit size for the memory result. That is a major redesign rather than a revision, which is why I recommend rejection of the present version with encouragement to resubmit a reworked study.

== Confidential Comments to Editor

#oranget[I recommend rejection.] The manuscript's defining problem is a category mismatch: it advertises an ECC-vs-RSA-in-ZKP study but benchmarks Poseidon/Merkle and an RSA-accumulator surrogate, so the central claims ("resource inversion," the hybrid recommendation) are not supported by the experiments. #purplet[The "scaling laws" are tautological — they reproduce known per-unit constraint costs by repeating unit circuits, with $R^2 approx 1$ as a tell — and several key numbers (peak memory, proving time, the scaling constant, surrogate "security levels") are inconsistent across the abstract, body, tables, and figures.] The flagship resource result rests on $n=3$ replicates of ~260-constraint circuits where the authors admit the backend dominates, and the largest RSA prover measurements were never taken (compile-only, >128 GiB).

These are not editorial defects; they require redesigning the core experiments and reframing the contribution, and the residual novelty over existing classical ECC/RSA comparisons and existing ZK-hash/SNARK benchmarks (including the authors' ref [6]) is limited. #purplet[The reproducibility infrastructure is a real positive, and a substantially reworked study — with faithful in-circuit primitives or an honest surrogate framing, a non-tautological model, reconciled numbers, and adequate statistics — could be worth reconsidering as a new submission.]

// Bibliography section
// #bibliography("../references.bib", style: "apa")
